/// Flutter icons SkipitCustomAccessibilityIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SkipitCustomAccessibilityIcons
///      fonts:
///       - asset: fonts/CustomAccessibilityIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomAccessibilityIcons {
  CustomAccessibilityIcons._();

  static const _kFontFam = 'CustomAccessibilityIcons';
  static const _kFontPkg = null;

  static const IconData seats = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lift = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData escalators_down = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData escalators_up = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wheelchair = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stairs = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticketing = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike_parking = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilets = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_card = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_moment_outlined = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_from_gallery = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zones_filter = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_moment_filled = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zones_general = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatbot = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zones_tutorial = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accessibility = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tickets = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transport_maps = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
