name: lisbon_travel
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State manager
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.2.0
  # Models
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  # Network
  dio: ^4.0.6
  # Google / maps
  google_maps_flutter: ^2.2.5
  flutter_polyline_points: ^1.0.0
  # UI
  font_awesome_flutter: ^10.4.0
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  paginated_search_bar: ^1.1.2
  # Location
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  # Animation
  animations: ^2.0.7
  animated_size_and_fade: ^3.0.1
  animated_list_plus: ^0.5.0
  # Others
  envied: ^0.3.0
  easy_localization: ^3.0.2-dev.5
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  either_dart: ^0.3.0
  easy_debounce: ^2.0.3
  flutter_keyboard_visibility: ^5.4.0
  uuid: ^4.0.0-beta3-1
  async_builder: ^1.3.1+1
  flutter_svg: ^2.0.5
  flutter_mailer: ^2.0.2
  collection: any
  queue: any
  google_directions_api:
    git:
      url: https://github.com/SamadiPour/google_directions_api.git
      ref: patch-2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  envied_generator: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_gen_runner: ^5.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map_icons/
    - assets/accessibility_icons/
    - i18n/

  fonts:
    - family: CustomAccessibilityIcons
      fonts:
        - asset: assets/fonts/CustomAccessibilityIcons.ttf
    - family: InfoBarIcon
      fonts:
        - asset: assets/fonts/InfoBarIcon.ttf

flutter_gen:
  output: lib/generated/
  line_length: 80
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
  fonts:
    enabled: true
  colors:
    enabled: false