const Map<String, String> languageNames = {
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'አማርኛ',
  'ar': 'العربية',
  'as': 'অসমীয়া',
  'az': 'Azərbaycan',
  'be': 'Беларуская',
  'bg': 'Български',
  'bm': 'Bamanakan',
  'bn': 'বাংলা',
  'bo': 'བོད་སྐད་',
  'br': 'Brezhoneg',
  'bs': 'Bosanski',
  'ca': 'Català',
  'cs': 'Čeština',
  'cy': 'Cymraeg',
  'da': 'Dansk',
  'de': 'Deutsch',
  'dz': 'རྫོང་ཁ',
  'ee': 'Eʋegbe',
  'el': 'Ελληνικά',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Español',
  'et': 'Eesti',
  'eu': 'Euskara',
  'fa': 'فارسی',
  'ff': 'Pulaar',
  'fi': 'Suomi',
  'fo': 'Føroyskt',
  'fr': 'Français',
  'fy': 'West-Frysk',
  'ga': 'Gaeilge',
  'gd': 'Gàidhlig',
  'gl': 'Galego',
  'gu': 'ગુજરાતી',
  'gv': 'Gaelg',
  'ha': 'Hausa',
  'he': 'עברית',
  'hi': 'हिंदी',
  'hr': 'Hrvatski',
  'hu': 'Magyar',
  'hy': 'հայերեն',
  'id': 'Bahasa Indonesia',
  'ig': 'Igbo',
  'ii': 'ꆈꌠꉙ',
  'is': 'Íslenska',
  'it': 'Italiano',
  'ja': '日本語',
  'ka': 'ქართული',
  'ki': 'Gikuyu',
  'kk': 'Қазақ тілі',
  'kl': 'Kalaallisut',
  'km': 'ខ្មែរ',
  'kn': 'ಕನ್ನಡ',
  'ko': '한국어',
  'ks': 'کٲشُر',
  'kw': 'Kernewek',
  'ky': 'Кыргызча',
  'lb': 'Lëtzebuergesch',
  'lg': 'Luganda',
  'ln': 'Lingála',
  'lo': 'ລາວ',
  'lt': 'Lietuvių',
  'lu': 'Tshiluba',
  'lv': 'Latviešu',
  'mg': 'Malagasy',
  'mk': 'Македонски',
  'ml': 'മലയാളം',
  'mn': 'Монгол',
  'mr': 'मराठी',
  'ms': 'Bahasa Melayu',
  'mt': 'Malti',
  'my': 'ဗမာ',
  'nb': 'Bokmål',
  'nd': 'isiNdebele',
  'ne': 'नेपाली',
  'nl': 'Nederlands',
  'nn': 'Nynorsk',
  'no': 'Norsk',
  'om': 'Oromoo',
  'or': 'ଓଡ଼ିଆ',
  'os': 'Ирон',
  'pa': 'ਪੰਜਾਬੀ',
  'pl': 'Polski',
  'ps': 'پښتو',
  'pt': 'Português',
  'qu': 'Runasimi',
  'rm': 'Rumantsch',
  'rn': 'Ikirundi',
  'ro': 'Română',
  'ru': 'Pусский',
  'rw': 'Kinyarwanda',
  'se': 'Davvisámegiella',
  'sg': 'Sängö',
  'sh': 'Serbo-Croatian',
  'si': 'සිංහල',
  'sk': 'Slovenčina',
  'sl': 'Slovenščina',
  'sn': 'chiShona',
  'so': 'Soomaali',
  'sq': 'Shqip',
  'sr': 'Cрпски',
  'sv': 'Svenska',
  'sw': 'Kiswahili',
  'ta': 'தமிழ்',
  'te': 'తెలుగు',
  'th': 'ไทย',
  'ti': 'ትግርኛ',
  'tl': 'Tagalog',
  'to': 'Lea fakatonga',
  'tr': 'Türkçe',
  'ug': 'ئۇيغۇرچە',
  'uk': 'Українська',
  'ur': 'اردو',
  'uz': 'Oʻzbekcha',
  'vi': 'Tiếng Việt',
  'yi': 'ייִדיש',
  'yo': 'Èdè Yorùbá',
  'zh': '中文',
  'zu': 'IsiZulu',
};

// https://github.com/Bas950/Language-Flag-Colors/blob/main/src/languages.ts
const Map<String, String> languageFlags = {
  'en': '🇬🇧',
  'es': '🇪🇸',
  'de': '🇩🇪',
  'it': '🇮🇹',
  'da': '🇩🇰',
  'nl': '🇳🇱',
  'fr': '🇫🇷',
  'bg': '🇧🇬',
  'cs': '🇨🇿',
  'el': '🇬🇷',
  'hr': '🇭🇷',
  'hu': '🇭🇺',
  'fi': '🇫🇮',
  'pt': '🇵🇹',
  'no': '🇳🇴',
  'sv': '🇸🇪',
};
